CREATE TABLE tb_medicos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    crm VARCHAR(20) NOT NULL UNIQUE,
    especialidade VARCHAR(100),
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    usuario_id BIGINT UNIQUE,
    CONSTRAINT fk_medicos_usuarios FOREIGN KEY (usuario_id) REFERENCES tb_usuarios(id)
);